/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRelatoriosRouteImport } from './routes/_app.relatorios'
import { Route as AppProfissionaisRouteImport } from './routes/_app.profissionais'
import { Route as AppPacientesRouteImport } from './routes/_app.pacientes'
import { Route as AppFrequenciaRouteImport } from './routes/_app.frequencia'
import { Route as AppDiretoriaRouteImport } from './routes/_app.diretoria'
import { Route as AppDespesasRouteImport } from './routes/_app.despesas'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAgendaRouteImport } from './routes/_app.agenda'
import { Route as AppPacientesIdRouteImport } from './routes/_app.pacientes.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppProfissionaisRoute = AppProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesRoute = AppPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AppRoute,
} as any)
const AppFrequenciaRoute = AppFrequenciaRouteImport.update({
  id: '/frequencia',
  path: '/frequencia',
  getParentRoute: () => AppRoute,
} as any)
const AppDiretoriaRoute = AppDiretoriaRouteImport.update({
  id: '/diretoria',
  path: '/diretoria',
  getParentRoute: () => AppRoute,
} as any)
const AppDespesasRoute = AppDespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesIdRoute = AppPacientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPacientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AppAgendaRoute
  '/dashboard': typeof AppDashboardRoute
  '/despesas': typeof AppDespesasRoute
  '/diretoria': typeof AppDiretoriaRoute
  '/frequencia': typeof AppFrequenciaRoute
  '/pacientes': typeof AppPacientesRouteWithChildren
  '/profissionais': typeof AppProfissionaisRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/pacientes/$id': typeof AppPacientesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AppAgendaRoute
  '/dashboard': typeof AppDashboardRoute
  '/despesas': typeof AppDespesasRoute
  '/diretoria': typeof AppDiretoriaRoute
  '/frequencia': typeof AppFrequenciaRoute
  '/pacientes': typeof AppPacientesRouteWithChildren
  '/profissionais': typeof AppProfissionaisRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/pacientes/$id': typeof AppPacientesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/despesas': typeof AppDespesasRoute
  '/_app/diretoria': typeof AppDiretoriaRoute
  '/_app/frequencia': typeof AppFrequenciaRoute
  '/_app/pacientes': typeof AppPacientesRouteWithChildren
  '/_app/profissionais': typeof AppProfissionaisRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/pacientes/$id': typeof AppPacientesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/dashboard'
    | '/despesas'
    | '/diretoria'
    | '/frequencia'
    | '/pacientes'
    | '/profissionais'
    | '/relatorios'
    | '/pacientes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/dashboard'
    | '/despesas'
    | '/diretoria'
    | '/frequencia'
    | '/pacientes'
    | '/profissionais'
    | '/relatorios'
    | '/pacientes/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/agenda'
    | '/_app/dashboard'
    | '/_app/despesas'
    | '/_app/diretoria'
    | '/_app/frequencia'
    | '/_app/pacientes'
    | '/_app/profissionais'
    | '/_app/relatorios'
    | '/_app/pacientes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profissionais': {
      id: '/_app/profissionais'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof AppProfissionaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pacientes': {
      id: '/_app/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof AppPacientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/frequencia': {
      id: '/_app/frequencia'
      path: '/frequencia'
      fullPath: '/frequencia'
      preLoaderRoute: typeof AppFrequenciaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diretoria': {
      id: '/_app/diretoria'
      path: '/diretoria'
      fullPath: '/diretoria'
      preLoaderRoute: typeof AppDiretoriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/despesas': {
      id: '/_app/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof AppDespesasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pacientes/$id': {
      id: '/_app/pacientes/$id'
      path: '/$id'
      fullPath: '/pacientes/$id'
      preLoaderRoute: typeof AppPacientesIdRouteImport
      parentRoute: typeof AppPacientesRoute
    }
  }
}

interface AppPacientesRouteChildren {
  AppPacientesIdRoute: typeof AppPacientesIdRoute
}

const AppPacientesRouteChildren: AppPacientesRouteChildren = {
  AppPacientesIdRoute: AppPacientesIdRoute,
}

const AppPacientesRouteWithChildren = AppPacientesRoute._addFileChildren(
  AppPacientesRouteChildren,
)

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDespesasRoute: typeof AppDespesasRoute
  AppDiretoriaRoute: typeof AppDiretoriaRoute
  AppFrequenciaRoute: typeof AppFrequenciaRoute
  AppPacientesRoute: typeof AppPacientesRouteWithChildren
  AppProfissionaisRoute: typeof AppProfissionaisRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDespesasRoute: AppDespesasRoute,
  AppDiretoriaRoute: AppDiretoriaRoute,
  AppFrequenciaRoute: AppFrequenciaRoute,
  AppPacientesRoute: AppPacientesRouteWithChildren,
  AppProfissionaisRoute: AppProfissionaisRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
